### ISSUE TITLE
Add github CI action to run busted specs

### ISSUE THREAD

**Issue by codymikol** [codymikol/multiverse.nvim#29]

**Comment by codymikol** [comment]
Partial progress on branch `agent/issue-29` (draft PR #105).

**Pushed**: `.busted` root config (busted collects only `lua/test/**/*.spec.lua`, excludes the `.headless.lua` nvim-API tests; resolves `require("multiverse.*")` via `lpath = "lua/?.lua;lua/?/init.lua;;"`) plus `scripts/verify_busted_pattern.lua`, a regression check for that pattern run via `nvim --headless -l` (busted/luarocks/nix are all unavailable in the agent sandbox, so this was the closest executable verification available).

**Blocked**: the actual CI workflow file, `.github/workflows/busted.yml`, could not be pushed — GitHub rejected it with "refusing to allow a Personal Access Token to create or update workflow ... without `workflow` scope". This bot's token intentionally lacks that scope as a security boundary; I'm not attempting to route around it.

A human with `workflow` scope needs to add `.github/workflows/busted.yml` with this content (installs Lua 5.1 + luarocks via the standard `leafo/gh-actions-lua`/`leafo/gh-actions-luarocks` actions, then `luarocks install busted && busted`, which picks up the `.busted` config automatically):

```yaml
name: Busted

on:
  push:
  pull_request:

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Install busted
        run: luarocks install busted

      - name: Run busted specs
        run: busted
```

Once that's added (e.g. directly on this branch or a follow-up), issue #29 is fully resolved.
